/*! \file
    \brief Autogenerated enumerations (Umba Enum Gen)
 */

#pragma once


#include "marty_cpp/marty_enum.h"
#include "marty_cpp/marty_flag_ops.h"
#include "marty_cpp/marty_flags.h"

#include <exception>
#include <map>
#include <stdexcept>
#include <string>
#include <unordered_map>



namespace marty{
namespace svg{

//#!RoundRectFlags
enum class RoundRectFlags : std::uint32_t
{
    invalid            = (std::uint32_t)(-1) /*!<  */,
    unknown            = (std::uint32_t)(-1) /*!<  */,
    none               = 0x0000 /*!< No round rect angles at all */,
    noRound            = 0x0000 /*!< No round rect angles at all */,
    roundNone          = 0x0000 /*!< No round rect angles at all */,
    roundLeftTop       = 0x0001 /*!< Left top angle is round */,
    roundLeftBottom    = 0x0002 /*!< Left bottom angle is round */,
    roundRightTop      = 0x0004 /*!< Right top angle is round */,
    roundRightBottom   = 0x0008 /*!< Right bottom angle is round */,
    roundLeft          = roundLeftTop    | roundLeftBottom /*!< Left side angles are round */,
    roundRight         = roundRightTop   | roundRightBottom /*!< Right side angles are round */,
    roundTop           = roundLeftTop    | roundRightTop /*!< Top side angles are round */,
    roundBottom        = roundLeftBottom | roundRightBottom /*!< Bottom side angles are round */,
    round              = roundLeft | roundRight /*!< All angles are round */

}; // enum 
//#!

MARTY_CPP_MAKE_ENUM_FLAGS(RoundRectFlags)

MARTY_CPP_ENUM_FLAGS_SERIALIZE_BEGIN( RoundRectFlags, std::map, 1 )
    MARTY_CPP_ENUM_FLAGS_SERIALIZE_ITEM( RoundRectFlags::roundRightBottom   , "RoundRightBottom" );
    MARTY_CPP_ENUM_FLAGS_SERIALIZE_ITEM( RoundRectFlags::invalid            , "Invalid"          );
    MARTY_CPP_ENUM_FLAGS_SERIALIZE_ITEM( RoundRectFlags::none               , "None"             );
    MARTY_CPP_ENUM_FLAGS_SERIALIZE_ITEM( RoundRectFlags::roundLeftTop       , "RoundLeftTop"     );
    MARTY_CPP_ENUM_FLAGS_SERIALIZE_ITEM( RoundRectFlags::roundLeftBottom    , "RoundLeftBottom"  );
    MARTY_CPP_ENUM_FLAGS_SERIALIZE_ITEM( RoundRectFlags::roundRightTop      , "RoundRightTop"    );
    MARTY_CPP_ENUM_FLAGS_SERIALIZE_ITEM( RoundRectFlags::roundLeft          , "RoundLeft"        );
    MARTY_CPP_ENUM_FLAGS_SERIALIZE_ITEM( RoundRectFlags::roundRight         , "RoundRight"       );
    MARTY_CPP_ENUM_FLAGS_SERIALIZE_ITEM( RoundRectFlags::roundTop           , "RoundTop"         );
    MARTY_CPP_ENUM_FLAGS_SERIALIZE_ITEM( RoundRectFlags::roundBottom        , "RoundBottom"      );
    MARTY_CPP_ENUM_FLAGS_SERIALIZE_ITEM( RoundRectFlags::round              , "Round"            );
MARTY_CPP_ENUM_FLAGS_SERIALIZE_END( RoundRectFlags, std::map, 1 )

MARTY_CPP_ENUM_FLAGS_DESERIALIZE_BEGIN( RoundRectFlags, std::map, 1 )
    MARTY_CPP_ENUM_FLAGS_DESERIALIZE_ITEM( RoundRectFlags::roundRightBottom   , "round-right-bottom" );
    MARTY_CPP_ENUM_FLAGS_DESERIALIZE_ITEM( RoundRectFlags::roundRightBottom   , "roundrightbottom"   );
    MARTY_CPP_ENUM_FLAGS_DESERIALIZE_ITEM( RoundRectFlags::roundRightBottom   , "round_right_bottom" );
    MARTY_CPP_ENUM_FLAGS_DESERIALIZE_ITEM( RoundRectFlags::invalid            , "invalid"            );
    MARTY_CPP_ENUM_FLAGS_DESERIALIZE_ITEM( RoundRectFlags::invalid            , "unknown"            );
    MARTY_CPP_ENUM_FLAGS_DESERIALIZE_ITEM( RoundRectFlags::none               , "no-round"           );
    MARTY_CPP_ENUM_FLAGS_DESERIALIZE_ITEM( RoundRectFlags::none               , "none"               );
    MARTY_CPP_ENUM_FLAGS_DESERIALIZE_ITEM( RoundRectFlags::none               , "roundnone"          );
    MARTY_CPP_ENUM_FLAGS_DESERIALIZE_ITEM( RoundRectFlags::none               , "no_round"           );
    MARTY_CPP_ENUM_FLAGS_DESERIALIZE_ITEM( RoundRectFlags::none               , "noround"            );
    MARTY_CPP_ENUM_FLAGS_DESERIALIZE_ITEM( RoundRectFlags::none               , "round-none"         );
    MARTY_CPP_ENUM_FLAGS_DESERIALIZE_ITEM( RoundRectFlags::none               , "round_none"         );
    MARTY_CPP_ENUM_FLAGS_DESERIALIZE_ITEM( RoundRectFlags::roundLeftTop       , "round-left-top"     );
    MARTY_CPP_ENUM_FLAGS_DESERIALIZE_ITEM( RoundRectFlags::roundLeftTop       , "round_left_top"     );
    MARTY_CPP_ENUM_FLAGS_DESERIALIZE_ITEM( RoundRectFlags::roundLeftTop       , "roundlefttop"       );
    MARTY_CPP_ENUM_FLAGS_DESERIALIZE_ITEM( RoundRectFlags::roundLeftBottom    , "round-left-bottom"  );
    MARTY_CPP_ENUM_FLAGS_DESERIALIZE_ITEM( RoundRectFlags::roundLeftBottom    , "round_left_bottom"  );
    MARTY_CPP_ENUM_FLAGS_DESERIALIZE_ITEM( RoundRectFlags::roundLeftBottom    , "roundleftbottom"    );
    MARTY_CPP_ENUM_FLAGS_DESERIALIZE_ITEM( RoundRectFlags::roundRightTop      , "round-right-top"    );
    MARTY_CPP_ENUM_FLAGS_DESERIALIZE_ITEM( RoundRectFlags::roundRightTop      , "roundrighttop"      );
    MARTY_CPP_ENUM_FLAGS_DESERIALIZE_ITEM( RoundRectFlags::roundRightTop      , "round_right_top"    );
    MARTY_CPP_ENUM_FLAGS_DESERIALIZE_ITEM( RoundRectFlags::roundLeft          , "round-left"         );
    MARTY_CPP_ENUM_FLAGS_DESERIALIZE_ITEM( RoundRectFlags::roundLeft          , "round_left"         );
    MARTY_CPP_ENUM_FLAGS_DESERIALIZE_ITEM( RoundRectFlags::roundLeft          , "roundleft"          );
    MARTY_CPP_ENUM_FLAGS_DESERIALIZE_ITEM( RoundRectFlags::roundRight         , "round-right"        );
    MARTY_CPP_ENUM_FLAGS_DESERIALIZE_ITEM( RoundRectFlags::roundRight         , "round_right"        );
    MARTY_CPP_ENUM_FLAGS_DESERIALIZE_ITEM( RoundRectFlags::roundRight         , "roundright"         );
    MARTY_CPP_ENUM_FLAGS_DESERIALIZE_ITEM( RoundRectFlags::roundTop           , "round-top"          );
    MARTY_CPP_ENUM_FLAGS_DESERIALIZE_ITEM( RoundRectFlags::roundTop           , "round_top"          );
    MARTY_CPP_ENUM_FLAGS_DESERIALIZE_ITEM( RoundRectFlags::roundTop           , "roundtop"           );
    MARTY_CPP_ENUM_FLAGS_DESERIALIZE_ITEM( RoundRectFlags::roundBottom        , "round-bottom"       );
    MARTY_CPP_ENUM_FLAGS_DESERIALIZE_ITEM( RoundRectFlags::roundBottom        , "round_bottom"       );
    MARTY_CPP_ENUM_FLAGS_DESERIALIZE_ITEM( RoundRectFlags::roundBottom        , "roundbottom"        );
    MARTY_CPP_ENUM_FLAGS_DESERIALIZE_ITEM( RoundRectFlags::round              , "round"              );
MARTY_CPP_ENUM_FLAGS_DESERIALIZE_END( RoundRectFlags, std::map, 1 )

} // namespace svg
} // namespace marty

